
import ProductView from "@/components/ProductView";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Barcha Mahsulotlar",
  description: "Generated by create next app",
};

const Product = async () => {
  const response = await fetch("https://fakestoreapi.com/products", {
    next: { revalidate: 60 },
  });
  const data = await response.json();

  return (
    <div>
      <ProductView products={data} />
    </div>
  );
};

export default Product;
