import UserView from "@/components/UserView";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Barcha Userlar",
  description: "Generated by create next app",
};

const User = async () => {
  const response = await fetch("https://fakestoreapi.com/users", {
    cache: "force-cache",
  });
  const data = await response.json();

  return (
    <div>
      <UserView data={data} />
    </div>
  );
};

export default User;
